(()=>{"use strict";
const D=document.getElementById("walkthrough-dialog");if(!D)return;
const flows={
book:{k:"PROJECT UNVEILED",t:"See the work before you buy it.",l:"The public reader stays free. The paid edition is a way to own the downloadable work and directly support continued research.",s:[
["THE QUESTION","What if some of what you inherited deserves another look?","Project Unveiled follows Scripture, history, empire, doctrine and fruit while keeping evidence and interpretation distinguishable."],
["THE WORK","Read before committing.","Start with the complete public reader. Examine the argument, sources and research posture for yourself."],
["THE EDITION","Own the downloadable edition.","The $7 edition includes the complete digital book: thirteen chapters and five research appendices."],
["THE NEXT STEP","Choose after you understand it.","There is no countdown and no claim that buying proves agreement."]],final:'<a class="button" href="/book/read/">Read free first</a><a class="button secondary" href="https://paypal.me/Bobsome1975/7USD" target="_blank" rel="noopener noreferrer" data-pu-event="product_checkout_click" data-product="project-unveiled-digital">Get the $7 edition</a><p class="fine">Current fulfillment is personal, not instant. After payment, send Robert the PayPal transaction number and delivery email.</p>'},
journey:{k:"7-DAY UNVEILED JOURNEY",t:"Start with one honest question.",l:"A smaller entry point for readers who want to investigate without beginning with the whole book.",s:[["DAY 1","One Scripture.","Begin with the text rather than somebody else's conclusion."],["REFLECT","One truth to examine.","Separate what the passage says from what has been added to it."],["QUESTION","One honest question.","Carry the question forward without being forced into a predetermined verdict."],["CONTINUE","Seven days, freely available.","Use the journey as a doorway into the larger evidence trail."]],final:'<a class="button" href="/unveiled/?utm_source=store&utm_medium=owned&utm_campaign=revenue_funnel&utm_content=walkthrough">Begin the free journey</a>'},
truth:{k:"TRUST-WORTHY RESEARCH",t:"Watch a claim become an evidence file.",l:"The objective is not to make a claim sound true. It is to make the reasoning inspectable.",s:[["1 · ORIGIN","Where did the claim come from?","Find the earliest attributable source and distinguish repetition from independent corroboration."],["2 · TEST","What is the strongest evidence on both sides?","Look for primary material, counterevidence, contradictions and missing context."],["3 · LABEL","What do we actually know?","Mark verified fact, supported inference, contested interpretation and missing evidence separately."],["4 · AUDIT","Can somebody else inspect the path?","Sources, limitations, uncertainty and corrections stay visible. The audit trail is the product."]],final:'<a class="button" href="/truth/">Open the research desk</a>'},
visibility:{k:"VISIBILITY STARTER · $250",t:"Your business may not need more advertising.",l:"It may need a clearer path from “I found you” to “I bought.”",s:[["1 · LOOK","Inspect the customer path.","Review the website, social presence, offer and calls to action from a prospect’s point of view."],["2 · ISOLATE","Find the friction.","Prioritize five fixes instead of burying the owner under a generic audit."],["3 · BUILD","Create something usable.","Produce three promotional graphics with captions around one real offer, with one revision round."],["4 · AGREE","Define scope before payment.","Written scope and delivery date come first. Payment does not silently authorize expanded work."]],final:'<a class="button" href="mailto:thebobsomest1@gmail.com?subject=Visibility%20Starter%20scope&body=Business%3A%0AWebsite%3A%0AWhat%20I%20need%20customers%20to%20do%3A%0ABiggest%20problem%20I%20see%3A%0ADeadline%3A">Show Robert the bottleneck</a><a class="button secondary" href="https://www.paypal.com/ncp/payment/X77R4KF9E2VXC" target="_blank" rel="noopener noreferrer">Payment after scope agreement</a>'},
bottleneck:{k:"MEDIA + IT",t:"Start with the problem—not a mystery package.",l:"The fastest useful build begins by identifying where attention, revenue or workflow is breaking.",s:[["OBSERVE","What should be happening?","Define the customer or staff action the system is supposed to make easy."],["TRACE","Where does the path break?","Website, app, promotion, automation or workflow: isolate the actual friction before adding tools."],["SCOPE","Choose the smallest useful fix.","Set a concrete deliverable, boundary and delivery date."],["PROVE","Make the improvement visible.","Ship work that can be inspected rather than selling vague ongoing activity."]],final:'<a class="button" href="mailto:thebobsomest1@gmail.com?subject=Bobsome1%20business%20bottleneck&body=What%20I%20run%3A%0AWhat%20should%20be%20happening%3A%0AWhere%20it%20seems%20to%20break%3A%0AWhat%20a%20win%20looks%20like%3A%0ADeadline%3A">Bring Robert the problem</a><a class="button secondary" href="/services/">See capabilities</a>'},
sponsor:{k:"EVIDENCE SPONSORSHIP",t:"Fund the work, not the conclusion.",l:"Sponsorship can support a public evidence file without purchasing its verdict.",s:[["NAME","Name the project.","The funded investigation is clearly identified."],["DISCLOSE","Make support visible.","Relevant funding is disclosed rather than hidden behind the work."],["SEPARATE","Protect the conclusion.","Sources, counterevidence, limitations and corrections remain part of the public record."],["PUBLISH","Let the evidence stand.","No guaranteed conclusion, praise or suppression of inconvenient findings."]],final:'<a class="button" href="mailto:thebobsomest1@gmail.com?subject=Evidence%20file%20sponsorship&body=Organization%3A%0AProject%20or%20question%3A%0AWhat%20we%20can%20contribute%3A%0AWhat%20we%20need%20in%20return%3A%0ATimeline%3A">Propose a sponsorship</a>'},
technology:{k:"TECHNOLOGY TESTING",t:"A demonstration is not the same as field use.",l:"Put hardware, software, hosting or access into a real, bounded test and report what actually happens.",s:[["DEFINE","Define the test.","State the use case, equipment or software and what is actually being evaluated."],["USE","Put it into real work.","Evaluate it in a relevant workflow rather than repeating marketing claims."],["DOCUMENT","Record results and limits.","Separate observation from interpretation and disclose material constraints."],["REPORT","Publish honestly.","No guaranteed praise. Useful failures and limitations count as findings too."]],final:'<a class="button" href="mailto:thebobsomest1@gmail.com?subject=Technology%20testing%20proposal&body=Company%3A%0ATechnology%3A%0AProposed%20test%3A%0AWhat%20you%20can%20provide%3A%0ATimeline%3A">Offer technology to test</a>'},
local:{k:"REGIONAL PARTNERSHIP",t:"Visitors experience a trip—not isolated businesses.",l:"A stronger local package can connect separate services into one easier visitor path.",s:[["MAP","Start with the visitor.","What are they coming to the Table Rock Lake / Branson area to do?"],["CONNECT","Join complementary offers.","Lodging, food, attractions and transportation can solve different pieces of the same trip."],["PACKAGE","Make the path understandable.","Define who provides what, what the visitor receives and how each partner benefits."],["LAUNCH","Promote a real package.","No invented savings, demand or results. State the offer as it actually exists."]],final:'<a class="button" href="mailto:thebobsomest1@gmail.com?subject=Regional%20package%20proposal&body=Business%3A%0AWhat%20we%20offer%3A%0AIdeal%20visitor%3A%0APackage%20idea%3A%0ATimeline%3A">Build a local package</a>'}
};
let flow=null,i=0,last=null;const $=s=>D.querySelector(s), content=$("#walk-content"),final=$("#walk-final");
function render(){const step=flow.s[i];$("#walk-kicker").textContent=flow.k;$("#walk-title").textContent=flow.t;$("#walk-lead").textContent=flow.l;content.innerHTML='<p class="step-count">STEP '+(i+1)+' OF '+flow.s.length+'</p><h3>'+step[0]+'</h3><strong>'+step[1]+'</strong><p>'+step[2]+'</p>';$(".walk-progress").innerHTML=flow.s.map((_,n)=>'<i class="'+(n<=i?"on":"")+'"></i>').join("");$(".walk-prev").disabled=i===0;$(".walk-next").textContent=i===flow.s.length-1?"See next actions":"Next →";final.innerHTML=""}
document.querySelectorAll("[data-walkthrough]").forEach(b=>b.addEventListener("click",()=>{flow=flows[b.dataset.walkthrough];if(!flow)return;i=0;last=b;render();D.showModal()}));
$(".walk-next").addEventListener("click",()=>{if(i<flow.s.length-1){i++;render()}else{$(".walk-next").hidden=true;$(".walk-prev").hidden=true;content.innerHTML="";$(".walk-progress").innerHTML="";final.innerHTML=flow.final}});
$(".walk-prev").addEventListener("click",()=>{if(i>0){i--;render()}});
$(".close").addEventListener("click",()=>D.close());D.addEventListener("close",()=>{$(".walk-next").hidden=false;$(".walk-prev").hidden=false;if(last)last.focus()});
document.querySelectorAll("[data-intent]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.intent;document.querySelectorAll("[data-intent]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".offer-group").forEach(x=>x.classList.toggle("intent-match",x.dataset.audience===a||x.querySelector('[data-audience="'+a+'"]')));const first=document.querySelector(".offer-group.intent-match");document.querySelector(".intent-status").textContent="Showing the strongest starting points for: "+b.querySelector("strong").textContent;if(first)first.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"})}));
})();