<?php
declare(strict_types=1);
session_start();
header('Cache-Control: no-store, max-age=0');
header('X-Content-Type-Options: nosniff');
require_once dirname(__DIR__,2).'/truth/lib/ollama-provider.php';
if(empty($_SESSION['tw_csrf'])) $_SESSION['tw_csrf']=bin2hex(random_bytes(24));
$items=array_reverse(tw_read_questions()); $cfg=tw_ollama_config(); $usage=tw_usage();
function h(string $v): string { return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); }
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Trust-Worthy Research Queue</title><link rel="stylesheet" href="/truth/truth-worthy.css"></head><body><header class="topbar"><div class="wrap nav"><a class="brand" href="/owner/">OWNER <span>TRUST-WORTHY</span></a></div></header><main><section class="section"><div class="wrap"><div class="eyebrow">ADMIN-ONLY SHADOW PILOT</div><h1>Research Queue</h1><article class="card"><h2>Guardrails</h2><p><strong>State:</strong> <?=tw_research_enabled()?'ENABLED':'DISABLED'?> · <strong>Key:</strong> <?=tw_ollama_key()!==''?'configured':'missing'?> · <strong>Runs today:</strong> <?=(int)$usage['runs']?> / <?=(int)$cfg['daily_runs']?> · <strong>Reserved:</strong> $<?=number_format((float)$usage['reserved_usd'],2)?> / $<?=number_format((float)$cfg['daily_cost_usd'],2)?></p><p>Public submissions only enter this queue. Every result remains a private draft until a human reviews it.</p><?php if(tw_research_enabled()):?><form method="post" action="off.php"><input type="hidden" name="csrf" value="<?=h($_SESSION['tw_csrf'])?>"><button class="button" type="submit">Disable research now</button></form><?php endif;?></article>
<?php foreach($items as $item): if(!is_array($item))continue; $research=is_array($item['research']??null)?$item['research']:[];?><article class="card"><div class="case-id"><?=h((string)($item['id']??''))?> · <?=h(strtoupper((string)($item['status']??'queued')))?></div><h2><?=h((string)($item['question']??''))?></h2><p><?=h((string)($item['context']??''))?></p><?php if(($item['status']??'')==='queued'):?><form method="post" action="run.php"><input type="hidden" name="csrf" value="<?=h($_SESSION['tw_csrf'])?>"><input type="hidden" name="id" value="<?=h((string)$item['id'])?>"><button class="button" type="submit">Run bounded draft</button></form><?php else:?><p><strong>Proposition:</strong> <?=h((string)($research['proposition']??''))?></p><p><strong>Draft finding:</strong> <?=h((string)($research['draft_finding']??''))?></p><p><strong>Uncertainty:</strong> <?=h((string)($research['uncertainty']??'high'))?> · <strong>Human verdict:</strong> <?=h((string)($research['human_verdict']??'Not reviewed'))?></p><p><a class="button" href="review.php?id=<?=urlencode((string)$item['id'])?>">Inspect evidence & review</a></p><?php endif;?></article><?php endforeach;?>
</div></section></main></body></html>
