<?php
declare(strict_types=1);
session_start(); header('Cache-Control: no-store, max-age=0'); require_once dirname(__DIR__,2).'/truth/lib/trust-worthy-queue.php';
function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
$id=preg_replace('/[^a-f0-9]/','',(string)($_GET['id']??$_POST['id']??'')); $found=tw_find_question($id); if($found===null){http_response_code(404);exit('Queue item not found.');} [$index,$item]=$found;
if(empty($_SESSION['tw_csrf']))$_SESSION['tw_csrf']=bin2hex(random_bytes(24));
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 if(!hash_equals((string)$_SESSION['tw_csrf'],(string)($_POST['csrf']??''))){http_response_code(403);exit('Request rejected.');}
 $decision=(string)($_POST['decision']??''); if(!in_array($decision,['approved','rejected','needs-work'],true)){http_response_code(422);exit('Invalid decision.');}
 $item['research']['human_verdict']=$decision; $item['research']['human_notes']=tw_clean((string)($_POST['notes']??''),4000); $item['research']['human_reviewed_at_utc']=gmdate('c'); $item['status']='reviewed';
 if(!tw_replace_question($index,$item)){http_response_code(500);exit('Review could not be saved.');} header('Location: review.php?id='.rawurlencode($id),true,303);exit;
}
$r=is_array($item['research']??null)?$item['research']:[];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Review Draft</title><link rel="stylesheet" href="/truth/truth-worthy.css"></head><body><main><section class="section"><div class="wrap"><p><a href="index.php">← Queue</a></p><div class="eyebrow">HUMAN REVIEW REQUIRED</div><h1><?=h((string)($item['question']??''))?></h1><article class="card"><h2>Proposition</h2><p><?=h((string)($r['proposition']??''))?></p><h2>Evidence ledger</h2><ul class="rules"><?php foreach(($r['sources']??[]) as $s):if(!is_array($s))continue;?><li><strong><?=h((string)($s['id']??''))?>:</strong> <a href="<?=h((string)($s['url']??''))?>" target="_blank" rel="noopener noreferrer"><?=h((string)($s['title']??'Source'))?></a><br><?=h((string)($s['snippet']??''))?></li><?php endforeach;?></ul><?php foreach(['facts'=>'Facts','inferences'=>'Inferences','disputed'=>'Disputed','counterevidence'=>'Counterevidence'] as $key=>$label):?><h2><?=h($label)?></h2><ul class="rules"><?php foreach(($r[$key]??[]) as $row):if(!is_array($row))continue;?><li><?=h((string)($row['claim']??''))?> [<?=h(implode(', ',(array)($row['source_ids']??[])))?>]</li><?php endforeach;?></ul><?php endforeach;?><h2>Unknowns</h2><ul class="rules"><?php foreach(($r['unknowns']??[]) as $v):?><li><?=h((string)$v)?></li><?php endforeach;?></ul><h2>Limitations</h2><ul class="rules"><?php foreach(($r['limitations']??[]) as $v):?><li><?=h((string)$v)?></li><?php endforeach;?></ul><h2>Draft finding</h2><p><?=h((string)($r['draft_finding']??''))?></p></article><article class="card"><h2>Human verdict</h2><p>Review linked sources before deciding. Approval records editorial review; it does not publish anything.</p><form method="post"><input type="hidden" name="csrf" value="<?=h($_SESSION['tw_csrf'])?>"><input type="hidden" name="id" value="<?=h($id)?>"><label>Notes<textarea name="notes" maxlength="4000"><?=h((string)($r['human_notes']??''))?></textarea></label><label>Decision<select name="decision" required><option value="">Choose…</option><option value="approved">Approved</option><option value="needs-work">Needs work</option><option value="rejected">Rejected</option></select></label><button class="button" type="submit">Save human review</button></form></article></div></section></main></body></html>
