<?php
$id = isset($_GET['id']) ? (string) $_GET['id'] : 'TW-BATTLE-000001';
if (!preg_match('/^TW-BATTLE-[0-9]{6}$/', $id)) { http_response_code(400); exit('Invalid battle ID.'); }
$file = __DIR__ . '/battles-public/' . $id . '.json';
if (!is_file($file)) { http_response_code(404); exit('Battle not found.'); }
$battle = json_decode((string) file_get_contents($file), true);
if (!is_array($battle)) { http_response_code(500); exit('Battle record is invalid.'); }
function e($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function side_name($battle,$side){ return $side === 'a' ? ($battle['participant_a_name'] ?? 'Participant A') : ($battle['participant_b_name'] ?? 'Participant B'); }
function score_total($scores){ return array_sum(array_map('intval', $scores ?: [])); }
?>
<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($id) ?> | Trust-Worthy Theology Battle</title><meta name="description" content="A structured Trust-Worthy Theology Battle with alternating evidence turns, independent research, public scoring, and final review."><link rel="stylesheet" href="/trust-worthy/assets/trust-worthy.css"><style>.battle-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.side-card{padding:1.25rem;border:1px solid var(--line);background:var(--panel)}.turn{margin:1rem 0;padding:1.2rem;border:1px solid var(--line);background:var(--panel)}.score-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.5rem}.score{padding:.7rem;border:1px solid rgba(255,255,255,.12);background:#080604}.score strong{display:block;color:var(--gold2);font-size:1.35rem}.research-state{padding:.9rem;border-left:4px solid var(--gold);background:rgba(215,173,81,.06)}@media(max-width:760px){.battle-grid,.score-grid{grid-template-columns:1fr}}</style></head><body>
<header class="site-header"><div class="container nav"><a class="brand" href="/">PROJECT <span>UNVEILED</span></a><div><a href="/trust-worthy/">Trust-Worthy</a><a href="/trust-worthy/method/">Method</a></div></div></header>
<main>
<section class="hero"><div class="container"><div class="case-id"><?= e($battle['battle_id']) ?> · <?= e(strtoupper($battle['status'])) ?></div><h1 style="font-size:clamp(2.6rem,6vw,5rem)">Theology Battle</h1><p class="lead">Alternating evidence. Independent research every turn. No popularity vote. No inherited verdict.</p></div></section>
<section class="section"><div class="container"><div class="battle-grid"><article class="side-card"><div class="eyebrow">P</div><h2><?= e(side_name($battle,'a')) ?></h2><p><?= e($battle['p']) ?></p></article><article class="side-card"><div class="eyebrow">not-P</div><h2><?= e(side_name($battle,'b')) ?></h2><p><?= e($battle['not_p']) ?></p></article></div></div></section>
<section class="section"><div class="container"><div class="research-state"><strong>Current turn:</strong> <?= e(side_name($battle,$battle['current_side'] ?? 'a')) ?>. Each submitted evidence turn must trigger fresh Trust-Worthy research before any score is posted.</div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Turn record</div><h2>Evidence, research, score</h2>
<?php if (empty($battle['turns'])): ?><div class="panel"><p>No scored turns yet. This room is ready for the first live evidence submission.</p><p class="muted">The production flow will capture a spoken turn, transcribe it, identify the proposition/evidence claim, run independent research, map provenance and source lineage, seek counterevidence, perform the power/incentive audit, and then score the turn.</p></div><?php endif; ?>
<?php foreach (($battle['turns'] ?? []) as $turn): ?><article class="turn"><div class="case-id">Turn <?= e($turn['turn_number']) ?> · <?= e(side_name($battle,$turn['side'])) ?> · <?= e($turn['position']) ?></div><h3>Submitted evidence</h3><p><?= e($turn['submission']) ?></p><h3>Trust-Worthy independent research</h3><p><?= e($turn['trust_research']['summary'] ?? '') ?></p><div class="score-grid"><?php foreach (($turn['scores'] ?? []) as $label=>$value): ?><div class="score"><span><?= e(str_replace('_',' ',$label)) ?></span><strong><?= e($value) ?>/5</strong></div><?php endforeach; ?></div><p><strong>Turn total:</strong> <?= e(score_total($turn['scores'] ?? [])) ?>/45</p><p><?= e($turn['score_explanation'] ?? '') ?></p></article><?php endforeach; ?>
</div></section>
<section class="section"><div class="container"><div class="battle-grid"><div class="panel"><div class="eyebrow">Participant A</div><h2><?= !empty($battle['passes']['a']) ? 'Passed' : 'Still presenting evidence' ?></h2></div><div class="panel"><div class="eyebrow">Participant B</div><h2><?= !empty($battle['passes']['b']) ? 'Passed' : 'Still presenting evidence' ?></h2></div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Final review</div><h2>Only after both sides are finished</h2><?php if (empty($battle['final_review'])): ?><div class="panel"><p>The final assessment is locked until both participants pass. Trust-Worthy must then conduct a fresh whole-case investigation, deduplicate repeated source lineages, attack the apparent leader, audit context/language/logic/power incentives, and compare which explanation best fits the complete reliable record.</p></div><?php else: ?><div class="finding"><p><?= e($battle['final_review']['rationale'] ?? '') ?></p><p><strong>Epistemic assessment:</strong> <?= e($battle['final_review']['epistemic_assessment'] ?? '') ?></p><p><strong>Battle winner:</strong> <?= e($battle['final_review']['battle_winner'] ?? '') ?></p></div><?php endif; ?></div></section>
</main><footer><div class="container">The battle score measures evidentiary performance. Reality is not decided by points. Every final assessment remains open to better evidence.</div></footer></body></html>