<?php
$id = isset($_GET['id']) ? (string) $_GET['id'] : 'TW-CASE-000001';
if (!preg_match('/^TW-CASE-[0-9]{6}$/', $id)) { http_response_code(400); exit('Invalid case ID.'); }
$files = glob(__DIR__ . '/cases-public/' . $id . '-v*.json') ?: [];
if (!$files) { http_response_code(404); exit('Case not found.'); }
usort($files, static function($a,$b){ preg_match('/-v(\d+)\.json$/',$a,$ma); preg_match('/-v(\d+)\.json$/',$b,$mb); return ((int)($mb[1]??0)) <=> ((int)($ma[1]??0)); });
$case = json_decode((string) file_get_contents($files[0]), true);
if (!is_array($case)) { http_response_code(500); exit('Case record is invalid.'); }
function e($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function list_items($items){ foreach (($items ?: []) as $item) echo '<li>'.e($item).'</li>'; }
function assessment_label($value){
  $map = [
    'supports-p' => 'Evidence supports P',
    'leans-p' => 'Evidence leans toward P',
    'insufficient' => 'Evidence insufficient to decide',
    'leans-not-p' => 'Evidence leans toward not-P',
    'supports-not-p' => 'Evidence supports not-P',
    'not-yet-investigated' => 'Not yet investigated'
  ];
  return $map[$value] ?? (string)$value;
}
?>
<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($case['title']) ?> | Trust-Worthy AI</title><meta name="description" content="A public Trust-Worthy Truth Trial showing a proposition, its contradiction, evidence, reasoning, epistemic limits, and challenge history."><link rel="canonical" href="https://bobsome1.com/trust-worthy/case.php?id=<?= rawurlencode($id) ?>"><link rel="stylesheet" href="/trust-worthy/assets/trust-worthy.css"></head><body>
<header class="site-header"><div class="container nav"><a class="brand" href="/">PROJECT <span>UNVEILED</span></a><div><a href="/trust-worthy/">Trust-Worthy</a><a href="/trust-worthy/method/">Method</a><a href="/trust-worthy/challenge.php?id=<?= rawurlencode($id) ?>">Challenge</a></div></div></header>
<main>
<section class="hero"><div class="container"><div class="case-head"><div><div class="case-id"><?= e($case['case_id']) ?> · VERSION <?= e($case['version']) ?></div><h1 style="font-size:clamp(2.7rem,6vw,5.2rem)"><?= e($case['title']) ?></h1><p class="lead"><?= e($case['claim']) ?></p></div><span class="status"><?= e($case['status']) ?></span></div></div></section>
<section class="section"><div class="container"><div class="finding"><div class="eyebrow">Current epistemic assessment · <?= e(assessment_label($case['finding']['epistemic_assessment'] ?? '')) ?></div><h2>Truth is one thing. Our access to it can be incomplete.</h2><div class="split"><div class="panel"><div class="eyebrow">P</div><h3><?= e($case['finding']['truth_proposition'] ?? '') ?></h3></div><div class="panel"><div class="eyebrow">not-P</div><h3><?= e($case['finding']['contradiction'] ?? '') ?></h3></div></div><p><?= e($case['finding']['summary']) ?></p><p><strong>Strongest objection:</strong> <?= e($case['finding']['strongest_objection']) ?></p><h3>What would change this assessment</h3><ul class="clean"><?php list_items($case['finding']['what_would_change_it']); ?></ul><div class="actions"><a class="button" href="/trust-worthy/challenge.php?id=<?= rawurlencode($id) ?>">Challenge This Finding</a></div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Atomic propositions</div><h2>What is actually being tested?</h2><?php foreach (($case['propositions'] ?? []) as $p): ?><article class="source"><span class="status"><?= e($p['proposition_id'] ?? '') ?> · <?= e(assessment_label($p['epistemic_status'] ?? '')) ?></span><h3>P: <?= e($p['p'] ?? '') ?></h3><?php if (!empty($p['not_p'])): ?><p><strong>not-P:</strong> <?= e($p['not_p']) ?></p><?php endif; ?><?php if (!empty($p['scope_notes'])): ?><p class="muted"><?= e($p['scope_notes']) ?></p><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="section"><div class="container"><div class="eyebrow">Hidden premises</div><h2>Assumptions</h2><ul class="clean"><?php list_items($case['assumptions'] ?? []); ?></ul></div></section>
<section class="section"><div class="container"><div class="split"><div><div class="eyebrow">Evidence for P</div><h2>What supports the proposition</h2><ul class="clean"><?php list_items($case['evidence_for_p'] ?? []); ?></ul></div><div><div class="eyebrow">Evidence for not-P</div><h2>What supports the contradiction</h2><ul class="clean"><?php list_items($case['evidence_for_not_p'] ?? []); ?></ul></div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Source record</div><h2>Primary and contextual evidence</h2><?php foreach (($case['sources'] ?? []) as $s): ?><article class="source"><span class="status"><?= e($s['source_type']) ?> · <?= e($s['position']) ?></span><h3><?= e($s['title']) ?></h3><small><?= e($s['citation'] ?? '') ?><?= !empty($s['date']) ? ' · '.e($s['date']) : '' ?></small><p><?= e($s['provenance_notes'] ?? '') ?></p><?php if (!empty($s['url'])): ?><a href="<?= e($s['url']) ?>" rel="noopener noreferrer">Open source</a><?php endif; ?></article><?php endforeach; ?></div></section>
<section class="section"><div class="container"><div class="split"><div><div class="eyebrow">Alternative hypotheses</div><h2>Other explanations of the same reality</h2><ul class="clean"><?php list_items($case['alternative_hypotheses'] ?? []); ?></ul></div><div><div class="eyebrow">Logic audit</div><h2>What must not be overstated</h2><ul class="clean"><?php list_items($case['logic_audit'] ?? []); ?></ul></div></div></div></section>
<?php if (!empty($case['christ_consistency'])): ?><section class="section"><div class="container"><div class="eyebrow">Theology mode</div><h2>Christ-consistency analysis</h2><div class="panel"><p><?= e($case['christ_consistency']['summary'] ?? '') ?></p><ul class="clean"><?php list_items($case['christ_consistency']['cautions'] ?? []); ?></ul></div></div></section><?php endif; ?>
<section class="section"><div class="container"><div class="eyebrow">Epistemic limits</div><h2>What we do not know yet</h2><p class="muted">Unknown to us is not a third truth value. It means the available evidence does not yet let us establish which proposition describes reality.</p><ul class="clean"><?php list_items($case['epistemic_limits'] ?? []); ?></ul></div></section>
<section class="section"><div class="container"><div class="eyebrow">Version history</div><h2>No silent rewrites</h2><div class="history"><?php foreach (($case['history'] ?? []) as $h): ?><div class="history-item"><strong>Version <?= e($h['version'] ?? '?') ?></strong> · <?= e($h['date'] ?? '') ?><br><span class="muted"><?= e($h['reason'] ?? '') ?></span></div><?php endforeach; ?></div></div></section>
</main><footer><div class="container">Reality does not change because people disagree about it. Trust-Worthy shows what the evidence presently permits us to know and invites you to test it. <a href="/trust-worthy/challenge.php?id=<?= rawurlencode($id) ?>">Bring better evidence.</a></div></footer></body></html>