<?php
$member = isset($_GET['member']) ? (string)$_GET['member'] : (isset($_POST['member_id']) ? (string)$_POST['member_id'] : '');
$positionId = isset($_GET['position']) ? (string)$_GET['position'] : (isset($_POST['position_id']) ? (string)$_POST['position_id'] : '');
if (!preg_match('/^TW-MEMBER-[A-Za-z0-9_-]+$/',$member) || !preg_match('/^[A-Za-z0-9_-]+$/',$positionId)) { http_response_code(400); exit('Invalid challenge target.'); }
$profileFile = __DIR__ . '/profiles-public/' . $member . '.json';
$profile = is_file($profileFile) ? json_decode((string)file_get_contents($profileFile), true) : null;
if (!is_array($profile)) { http_response_code(404); exit('Profile not found.'); }
$position = null; foreach (($profile['positions'] ?? []) as $p) { if (($p['position_id'] ?? '') === $positionId) { $position = $p; break; } }
if (!$position) { http_response_code(404); exit('Position not found.'); }
$notice='';$noticeClass='';
$types=['source/authenticity','provenance','chronology','translation/language','context','logic','counterevidence','assumption','omitted alternative'];
$targets=['p','not-p','evidence-for-p','evidence-for-not-p','assumption','logic','scope/definition'];
if ($_SERVER['REQUEST_METHOD']==='POST') {
  $honeypot=trim((string)($_POST['website']??'')); $type=trim((string)($_POST['challenge_type']??'')); $target=trim((string)($_POST['target_side']??''));
  $argument=trim((string)($_POST['argument']??'')); $source=trim((string)($_POST['source']??'')); $materiality=trim((string)($_POST['materiality']??'')); $name=trim((string)($_POST['display_name']??'')); $email=trim((string)($_POST['email']??''));
  if ($honeypot!=='') { http_response_code(400); $notice='Submission rejected.'; $noticeClass='error'; }
  elseif (!in_array($type,$types,true) || !in_array($target,$targets,true) || strlen($argument)<20 || strlen($materiality)<10) { $notice='Please identify the exact proposition/evidence target and explain why your evidence materially changes it.'; $noticeClass='error'; }
  elseif ($email!=='' && !filter_var($email,FILTER_VALIDATE_EMAIL)) { $notice='Please enter a valid email address or leave it blank.'; $noticeClass='error'; }
  else {
    $record=['challenge_id'=>'TW-MCH-'.gmdate('YmdHis').'-'.bin2hex(random_bytes(3)),'member_id'=>$member,'position_id'=>$positionId,'submitted_at'=>date(DATE_ATOM),'challenge_type'=>$type,'target_side'=>$target,'argument'=>$argument,'source'=>$source,'materiality'=>$materiality,'display_name'=>$name,'email'=>$email,'battle_invite'=>isset($_POST['battle_invite'])?'requested':'none','status'=>'pending-review'];
    $base=dirname((string)($_SERVER['DOCUMENT_ROOT']??__DIR__),1).'/private/trust-worthy/member-challenges'; if(!is_dir($base)){@mkdir($base,0700,true);} $file=$base.'/'.preg_replace('/[^A-Za-z0-9_-]/','_',$record['challenge_id']).'.json';
    if(is_dir($base)&&is_writable($base)&&file_put_contents($file,json_encode($record,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),LOCK_EX)!==false){@chmod($file,0600);$notice='Challenge received. Trust-Worthy must independently investigate the evidence. A live Theology Battle occurs only if the challenged member accepts.';$noticeClass='success';} else {http_response_code(503);$notice='The challenge could not be stored safely yet. Private intake storage must be configured before launch.';$noticeClass='error';}
  }
}
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Challenge a Theology Position | Trust-Worthy AI</title><link rel="stylesheet" href="/trust-worthy/assets/trust-worthy.css"></head><body>
<header class="site-header"><div class="container nav"><a class="brand" href="/">PROJECT <span>UNVEILED</span></a><div><a href="/trust-worthy/profile.php?member=<?= rawurlencode($member) ?>">Profile</a><a href="/trust-worthy/">Trust-Worthy</a></div></div></header>
<main><section class="hero"><div class="container"><div class="case-id"><?= e($member) ?> · <?= e($positionId) ?></div><h1 style="font-size:clamp(2.7rem,6vw,5rem)">Challenge the proposition.</h1><p class="lead"><strong>P:</strong> <?= e($position['p']) ?></p><?php if(!empty($position['not_p'])):?><p class="lead"><strong>not-P:</strong> <?= e($position['not_p']) ?></p><?php endif;?><div class="notice">Challenge the claim, evidence, translation, context, assumptions, or logic. Do not attack the member.</div></div></section>
<section class="section"><div class="container"><?php if($notice):?><div class="notice <?= e($noticeClass) ?>"><?= e($notice) ?></div><?php endif;?><form method="post" class="panel"><input type="hidden" name="member_id" value="<?= e($member) ?>"><input type="hidden" name="position_id" value="<?= e($positionId) ?>"><div style="position:absolute;left:-10000px" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><div class="form-grid"><div class="field"><label>Challenge type</label><select name="challenge_type" required><option value="">Choose one</option><?php foreach($types as $t):?><option><?= e($t) ?></option><?php endforeach;?></select></div><div class="field"><label>Target</label><select name="target_side" required><option value="">Choose one</option><?php foreach($targets as $t):?><option value="<?= e($t) ?>"><?= e($t) ?></option><?php endforeach;?></select></div><div class="field full"><label>Your argument</label><textarea name="argument" maxlength="6000" required></textarea></div><div class="field full"><label>Source URL or citation</label><input name="source" maxlength="1000"></div><div class="field full"><label>Why does this materially change the proposition?</label><textarea name="materiality" maxlength="3000" required></textarea></div><div class="field"><label>Public display name (optional)</label><input name="display_name" maxlength="100"></div><div class="field"><label>Email for follow-up (optional, private)</label><input name="email" type="email" maxlength="254"></div><div class="field full"><label><input type="checkbox" name="battle_invite" value="1"> Invite this member to an opt-in live Theology Battle if the challenge passes intake review.</label></div></div><button class="button" type="submit">Submit Evidence Challenge</button></form></div></section></main><footer><div class="container">No forced debates. Evidence challenges may stand asynchronously; live battles require acceptance.</div></footer></body></html>