<?php
$member = isset($_GET['member']) ? (string) $_GET['member'] : 'TW-MEMBER-founder';
if (!preg_match('/^TW-MEMBER-[A-Za-z0-9_-]+$/',$member)) { http_response_code(400); exit('Invalid member ID.'); }
$file = __DIR__ . '/profiles-public/' . $member . '.json';
if (!is_file($file)) { http_response_code(404); exit('Profile not found.'); }
$profile = json_decode((string)file_get_contents($file), true);
if (!is_array($profile) || ($profile['profile_visibility'] ?? 'private') !== 'public') { http_response_code(404); exit('Profile not found.'); }
function e($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
?>
<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($profile['display_name']) ?> | Theology Profile | Trust-Worthy AI</title><meta name="description" content="A public Trust-Worthy theology profile showing stated beliefs, evidence, challenges, and revision history."><link rel="stylesheet" href="/trust-worthy/assets/trust-worthy.css"></head><body>
<header class="site-header"><div class="container nav"><a class="brand" href="/">PROJECT <span>UNVEILED</span></a><div><a href="/trust-worthy/">Trust-Worthy</a><a href="/trust-worthy/method/">Method</a></div></div></header>
<main><section class="hero"><div class="container"><div class="case-id"><?= e($profile['member_id']) ?></div><h1 style="font-size:clamp(2.7rem,6vw,5rem)"><?= e($profile['display_name']) ?></h1><p class="lead"><?= e($profile['bio'] ?? '') ?></p><div class="notice">Confidence in a belief is compatible with letting others inspect and challenge the reasons for it. Challenges target propositions and evidence, never a person's worth or motives.</div></div></section>
<section class="section"><div class="container"><div class="eyebrow">Theology positions</div><h2>What this member currently holds</h2><?php foreach (($profile['positions'] ?? []) as $p): ?><article class="panel" style="margin:1rem 0"><div class="status"><?= e($p['topic']) ?> · <?= e($p['stance']) ?></div><h3><?= e($p['p']) ?></h3><?php if (!empty($p['not_p'])): ?><p><strong>Contradiction:</strong> <?= e($p['not_p']) ?></p><?php endif; ?><p><?= e($p['member_explanation'] ?? '') ?></p><h4>Evidence on record</h4><ul class="clean"><?php foreach (($p['evidence'] ?? []) as $ev): ?><li><strong><?= e($ev['position'] ?? '') ?></strong> — <?= e($ev['citation'] ?? '') ?><?= !empty($ev['note']) ? ': '.e($ev['note']) : '' ?></li><?php endforeach; ?></ul><?php if (!empty($p['linked_truth_trials'])): ?><p><strong>Linked Truth Trials:</strong> <?php foreach ($p['linked_truth_trials'] as $trial): ?><a href="/trust-worthy/case.php?id=<?= rawurlencode($trial) ?>"><?= e($trial) ?></a> <?php endforeach; ?></p><?php endif; ?><div class="actions"><a class="button" href="/trust-worthy/member-challenge.php?member=<?= rawurlencode($profile['member_id']) ?>&position=<?= rawurlencode($p['position_id']) ?>">Challenge This Belief</a></div><h4>Revision ledger</h4><div class="history"><?php foreach (($p['revision_history'] ?? []) as $h): ?><div class="history-item"><strong><?= e($h['date'] ?? '') ?></strong> · <?= e($h['from'] ?? '') ?> → <?= e($h['to'] ?? '') ?><br><span class="muted"><?= e($h['reason'] ?? '') ?></span></div><?php endforeach; ?></div></article><?php endforeach; ?></div></section>
</main><footer><div class="container">Truth is not decided by profile ownership, popularity, or confidence. Examine the evidence.</div></footer></body></html>