(()=>{
'use strict';
const form=document.getElementById('investigationForm');
if(!form)return;
const workspace=document.getElementById('workspace');
const claimMapPanel=document.getElementById('claimMapPanel');
const confirmedMap=document.getElementById('confirmedMap');
const mapExpiry=document.getElementById('mapExpiry');
const resultPanel=document.getElementById('resultPanel');
const status=document.getElementById('systemStatus');
const mapButton=document.getElementById('mapButton');
const researchButton=document.getElementById('researchButton');
const rebuildMapButton=document.getElementById('rebuildMapButton');
const activity=document.getElementById('activity');
const sourceCount=document.getElementById('sourceCount');
const sourceFamilyCount=document.getElementById('sourceFamilyCount');
const receiptCount=document.getElementById('receiptCount');
const verdict=document.getElementById('verdict');
const probability=document.getElementById('probability');
const probabilityNote=document.getElementById('probabilityNote');
const analysis=document.getElementById('analysis');
const sourceList=document.getElementById('sourceList');
let receipts=0,uniqueSources=new Map(),sourceFamilies=new Set(),authorizationToken='',expiresAt=0,expiryTimer=0;

const log=(title,detail='')=>{const row=document.createElement('div');row.className='event';const b=document.createElement('b');b.textContent=title;row.appendChild(b);if(detail){const s=document.createElement('span');s.textContent=detail;row.appendChild(s)}activity.prepend(row)};
const stageState=(name,state)=>{const item=document.querySelector(`[data-stage="${name}"]`);if(!item)return;item.classList.remove('active','done');if(state)item.classList.add(state)};
const markActive=name=>{document.querySelectorAll('#stageList li.active').forEach(el=>el.classList.remove('active'));stageState(name,'active')};
const safeUrl=value=>{try{const u=new URL(value,location.origin);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}};
const goals=()=>[...form.querySelectorAll('input[name="goal"]:checked')].map(x=>x.value);
const baseData=()=>{const data=new URLSearchParams(new FormData(form));data.delete('goal');return data};

const updateExpiry=()=>{if(!mapExpiry)return;const left=Math.max(0,Math.ceil((expiresAt-Date.now())/1000));if(left<=0){mapExpiry.textContent='Authorization expired — rebuild the claim map';researchButton.disabled=true;return}const min=Math.floor(left/60),sec=left%60;mapExpiry.textContent=`Research authorization expires in ${min}:${String(sec).padStart(2,'0')}`};
const armExpiry=seconds=>{if(expiryTimer)clearInterval(expiryTimer);expiresAt=Date.now()+Math.max(1,Number(seconds)||1)*1000;researchButton.disabled=false;updateExpiry();expiryTimer=setInterval(updateExpiry,1000)};

const consumeReceipt=r=>{if(!r||typeof r!=='object')return;receipts++;receiptCount.textContent=String(receipts);stageState(r.stage,'done');const order=['decompose','origin','primary','corroboration','counter','context','synthesis'];const idx=order.indexOf(r.stage);if(idx>=0&&idx<order.length-1)markActive(order[idx+1]);if(Array.isArray(r.sources)){r.sources.forEach(src=>{if(!src||!src.url)return;uniqueSources.set(src.url,src);if(typeof src.family==='string'&&src.family)sourceFamilies.add(src.family)});sourceCount.textContent=String(uniqueSources.size);sourceFamilyCount.textContent=String(sourceFamilies.size)}let detail='';if(Number.isFinite(r.source_count)){const familyPart=Number.isFinite(r.source_family_count)?` across ${r.source_family_count} source famil${r.source_family_count===1?'y':'ies'}`:'';detail=`${r.source_count} URL${r.source_count===1?'':'s'}${familyPart} attached to this receipt`}if(r.evidence_floor_met===false)detail='Evidence floor not met — probability blocked';if(r.stage==='synthesis'&&r.evidence_floor_met===true&&Number.isFinite(r.source_family_count))detail=`Evidence floor met across ${r.source_family_count} source families; diversity is not proof of editorial independence`;log(r.label||r.stage||'Stage completed',detail)};
const renderComplete=result=>{resultPanel.hidden=false;status.textContent='COMPLETE';verdict.textContent=result.verdict||'UNRESOLVED';probability.textContent=Number.isFinite(result.probability)?`${result.probability}%`:'NO SCORE';const m=result&&result.metrics&&typeof result.metrics==='object'?result.metrics:{};const familyNote=Number.isFinite(m.source_families)?` across ${m.source_families} source families`:'';probabilityNote.textContent=Number.isFinite(result.probability)?`Evidence-conditioned experimental probability based on ${m.unique_sources||uniqueSources.size} unique URLs${familyNote}. Source-family diversity is not proof of independence.`:'Trust-Worthy refused to issue a probability because the evidence floor was not met.';analysis.textContent=result.analysis||'';sourceList.textContent='';(Array.isArray(result.sources)?result.sources:[]).forEach(src=>{const href=safeUrl(src.url||'');if(!href)return;const a=document.createElement('a');a.href=href;a.target='_blank';a.rel='noopener noreferrer';const family=typeof src.family==='string'&&src.family?` · ${src.family}`:'';a.textContent=(src.title||href)+family;sourceList.appendChild(a)});resultPanel.scrollIntoView({behavior:'smooth',block:'start'})};
const parseStream=async response=>{if(!response.ok){let msg=`Investigation request failed (${response.status})`;try{const body=await response.json();if(body&&body.message)msg=body.message}catch{}throw new Error(msg)}if(!response.body)throw new Error('Streaming response unavailable.');const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='';for(;;){const {value,done}=await reader.read();buffer+=decoder.decode(value||new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()||'';for(const line of lines){if(!line.trim())continue;let event;try{event=JSON.parse(line)}catch{continue}if(event.type==='start'){status.textContent='INVESTIGATING';markActive('decompose');log(event.label||'Investigation started')}else if(event.type==='receipt')consumeReceipt(event.receipt);else if(event.type==='complete')renderComplete(event.result||{});else if(event.type==='error')throw new Error(event.message||'Investigation failed.')}if(done)break}};

const requestClaimMap=async()=>{mapButton.disabled=true;researchButton.disabled=true;status.textContent='MAPPING CLAIM';try{const data=baseData();const response=await fetch('/truth/claim-map.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:data.toString(),credentials:'same-origin'});let body={};try{body=await response.json()}catch{}if(!response.ok||!body.ok)throw new Error(body.message||`Claim analysis failed (${response.status})`);if(typeof body.claim_map!=='string'||!body.claim_map.trim()||typeof body.authorization_token!=='string'||!body.authorization_token)throw new Error('Claim analysis returned an incomplete confirmation packet.');authorizationToken=body.authorization_token;confirmedMap.value=body.claim_map.trim();claimMapPanel.hidden=false;status.textContent='REVIEW CLAIM MAP';armExpiry(body.expires_in||900);claimMapPanel.scrollIntoView({behavior:'smooth',block:'start'})}catch(err){status.textContent='STOPPED';claimMapPanel.hidden=true;authorizationToken='';alert(err instanceof Error?err.message:'Claim analysis failed.')}finally{mapButton.disabled=false}};

const beginResearch=async()=>{const map=confirmedMap.value.trim();if(!authorizationToken){alert('Rebuild the claim map to obtain a new one-time research authorization.');return}if(!map){alert('The investigation map cannot be empty.');confirmedMap.focus();return}if(Date.now()>=expiresAt){alert('The one-time research authorization expired. Rebuild the claim map.');researchButton.disabled=true;return}researchButton.disabled=true;if(expiryTimer)clearInterval(expiryTimer);workspace.hidden=false;resultPanel.hidden=true;activity.textContent='';receipts=0;uniqueSources=new Map();sourceFamilies=new Set();sourceCount.textContent='0';sourceFamilyCount.textContent='0';receiptCount.textContent='0';document.querySelectorAll('#stageList li').forEach(el=>el.classList.remove('active','done'));markActive('decompose');status.textContent='CONNECTING';const data=baseData();data.set('goals',goals().join('; '));data.set('confirmed_map',map);data.set('authorization_token',authorizationToken);authorizationToken='';try{const response=await fetch('/truth/deep-stream.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:data.toString(),credentials:'same-origin'});await parseStream(response)}catch(err){status.textContent='STOPPED';log('Investigation stopped',err instanceof Error?err.message:'Unknown error');mapExpiry.textContent='Research authorization consumed — rebuild the claim map to retry'}finally{researchButton.disabled=true}};

form.addEventListener('submit',e=>{e.preventDefault();requestClaimMap()});
researchButton.addEventListener('click',beginResearch);
rebuildMapButton.addEventListener('click',()=>{authorizationToken='';claimMapPanel.hidden=true;workspace.hidden=true;status.textContent='DEFINE';requestClaimMap()});
document.querySelectorAll('[data-branch]').forEach(btn=>btn.addEventListener('click',()=>{log('Branch requested',btn.dataset.branch||'Further investigation');btn.disabled=true;btn.textContent='Queued for V2 branch engine'}));
})();