<?php
declare(strict_types=1);
header('Content-Type:text/html; charset=UTF-8');header('Cache-Control:no-store,max-age=0');header('X-Robots-Tag:noindex,nofollow,noarchive');header('X-Frame-Options:DENY');header('Referrer-Policy:no-referrer');
require __DIR__.'/bootstrap.php';
try{$config=fs_config();}catch(Throwable $e){http_response_code(503);exit('Configuration unavailable');}
$env=fs_env();session_name('pu_private_funnel_servant');session_set_cookie_params(['lifetime'=>0,'path'=>'/owner/funnel-servant/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']);session_start();
if(empty($_SESSION['authenticated'])||empty($_SESSION['last_seen'])||time()-(int)$_SESSION['last_seen']>14400){header('Location:/owner/funnel-servant/');exit;}$_SESSION['last_seen']=time();
if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(24));$csrf=(string)$_SESSION['csrf'];
function cs_h(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function cs_flash(string $m,string $t='ok'):void{$_SESSION['cs_flash']=['m'=>$m,'t'=>$t];}
function cs_redirect():never{header('Location:/owner/funnel-servant/campaign-studio.php');exit;}
$chapters=['chapter-01.html'=>'Chapter 1 · Truth Is Not Afraid of Questions','chapter-02.html'=>'Chapter 2 · The Way Before the Machine','chapter-03.html'=>'Chapter 3 · When Rome Put Its Hand on the Cross','chapter-04.html'=>'Chapter 4 · The Approved Shelf','chapter-05.html'=>'Chapter 5 · Who Hung the Veil Back Up?','chapter-06.html'=>'Chapter 6 · Having Eyes to See','chapter-07.html'=>'Chapter 7 · The Traditions of Men','chapter-08.html'=>'Chapter 8 · Sons and Daughters of the Light','chapter-09.html'=>'Chapter 9','chapter-10.html'=>'Chapter 10','chapter-11.html'=>'Chapter 11 · Voices Beyond the Shelf','chapter-12.html'=>'Chapter 12','chapter-13.html'=>'Chapter 13 · Tear the Veil'];
$platforms=['facebook'=>'Facebook','instagram'=>'Instagram','x'=>'X','threads'=>'Threads','linkedin'=>'LinkedIn','youtube'=>'YouTube','tiktok'=>'TikTok'];
$goals=['read'=>'Drive chapter reading','engage'=>'Start honest discussion','review'=>'Earn reader reviews','support'=>'Invite project support'];
if(($_SERVER['REQUEST_METHOD']??'')==='POST'){
 if(!hash_equals($csrf,(string)($_POST['csrf']??''))){cs_flash('Security token expired. Reload and try again.','bad');cs_redirect();}
 $action=(string)($_POST['action']??'');
 if($action==='create_campaign'){
  $title=fs_clean($_POST['title']??'',180);$hook=fs_clean($_POST['hook']??'',800);$body=fs_clean($_POST['body']??'',6000);$cta=fs_clean($_POST['cta']??'',300);$platform=array_key_exists((string)($_POST['platform']??''),$platforms)?(string)$_POST['platform']:'facebook';$goal=array_key_exists((string)($_POST['goal']??''),$goals)?(string)$_POST['goal']:'read';
  $chapter=array_key_exists((string)($_POST['chapter']??''),$chapters)?(string)$_POST['chapter']:'chapter-01.html';$destination='/book/read/'.$chapter;$hashtags=fs_clean($_POST['hashtags']??'#ProjectUnveiled #TruthIsNotAfraidOfQuestions',600);$campaign=fs_slug($_POST['campaign_slug']??($title.'-'.gmdate('Ymd')),'project-unveiled-'.gmdate('Ymd'));$content=fs_slug($_POST['content_label']??('studio-'.$platform),'studio-'.$platform);
  $quality=fs_campaign_quality($title,$hook,$body,$cta,$destination,$config);$id=substr(bin2hex(random_bytes(8)),0,12);$post=trim(implode("\n\n",array_filter([$hook,$body,$cta],fn($v)=>trim((string)$v)!=='')));
  $draft=['id'=>$id,'created_at_utc'=>gmdate('c'),'source'=>'campaign-studio-v7.2','status'=>'draft','generation_version'=>'7.2-campaign-studio','title'=>$title,'strategy_title'=>fs_clean($_POST['strategy_title']??'',180),'platform'=>$platform,'goal'=>$goal,'hook'=>$hook,'body'=>$body,'cta'=>$cta,'hashtags'=>$hashtags,'destination_url'=>$destination,'tracked_url'=>$destination,'campaign_slug'=>$campaign,'content_label'=>$content,'post_copy'=>$post,'quality'=>$quality,'action_brief'=>['public_title'=>$title,'public_hook'=>$hook,'public_body'=>$body,'public_cta'=>$cta,'destination_url'=>$destination,'campaign_slug'=>$campaign,'content_label'=>$content,'platform'=>$platform]];
  if($title===''||$hook===''||$body===''||$cta===''){cs_flash('Title, hook, message, and call to action are required.','bad');}
  elseif(!empty($quality['blocked'])){cs_flash('Campaign was not saved because the locked quality gate found: '.implode(' ',array_slice((array)$quality['critical'],0,3)),'bad');}
  else{$drafts=fs_load_drafts();array_unshift($drafts,$draft);if(fs_save_drafts($drafts)){fs_log('campaign_studio','Campaign Studio draft created',['id'=>$id,'score'=>$quality['score'],'platform'=>$platform]);cs_flash('Campaign saved at '.$quality['score'].'/100 and is ready for owner review.');}else cs_flash('The campaign could not be saved.','bad');}
  cs_redirect();
 }
 if($action==='load_publisher'){$id=fs_clean($_POST['id']??'',30);[$ok,$msg]=fs_publisher_from_draft($id,$config);fs_log('campaign_studio_handoff',$msg,['id'=>$id,'ok'=>$ok]);if($ok){$_SESSION['flash']=['message'=>$msg,'type'=>'ok'];header('Location:/owner/funnel-servant/?tab=publisher');exit;}cs_flash($msg,'bad');cs_redirect();}
 if($action==='delete_campaign'){$id=fs_clean($_POST['id']??'',30);$drafts=array_values(array_filter(fs_load_drafts(),fn($d)=>!is_array($d)||(string)($d['id']??'')!==$id));fs_save_drafts($drafts);fs_log('campaign_studio','Campaign draft deleted',['id'=>$id]);cs_flash('Private draft deleted.');cs_redirect();}
}
$flash=$_SESSION['cs_flash']??null;unset($_SESSION['cs_flash']);$drafts=fs_load_drafts();$studio=array_values(array_filter($drafts,fn($d)=>is_array($d)&&($d['source']??'')==='campaign-studio-v7.2'));$settings=fs_settings();$defaultPlatform=(string)($settings['autopilot_preferred_platform']??'facebook');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Campaign Studio · Project Unveiled OS</title><link rel="stylesheet" href="campaign-studio.css"><script defer src="campaign-studio.js"></script></head><body><div class="studio-shell">
<header class="studio-head"><div><div class="eyebrow">PROJECT UNVEILED OS · V7.2</div><h1>Campaign Studio</h1><p>Build one reader-facing campaign from source to platform handoff. Every draft stays private, uses a clean destination, and must pass the locked quality gate before Post Now.</p></div><div class="top-actions"><a class="button secondary" href="command-center.php">Command Center</a><a class="button secondary" href="?tab=activity">Reports</a><a class="button" href="?tab=publisher">Post Now</a></div></header>
<div class="steps"><span class="active">1 Source</span><span class="active">2 Goal</span><span class="active">3 Message</span><span class="active">4 Platform</span><span class="active">5 Quality</span><span class="active">6 Handoff</span></div>
<?php if(is_array($flash)):?><div class="<?=($flash['t']??'ok')==='bad'?'bad':'saved'?>"><?=cs_h($flash['m']??'')?></div><?php endif;?>
<div class="studio-grid"><section class="panel"><div class="eyebrow">GUIDED CAMPAIGN BUILDER</div><h2>Create the next campaign</h2><div class="top-actions"><button class="secondary" type="button" data-template="questions">Questions</button><button class="secondary" type="button" data-template="love">Love Test</button><button class="secondary" type="button" data-template="costume">Kingdom or Costume</button><button class="secondary" type="button" data-template="veil">Torn Veil</button></div>
<form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=cs_h($csrf)?>"><input type="hidden" name="action" value="create_campaign"><label>Source chapter<select name="chapter"><?php foreach($chapters as $v=>$l):?><option value="<?=cs_h($v)?>"><?=cs_h($l)?></option><?php endforeach;?></select></label><label>Campaign goal<select name="goal"><?php foreach($goals as $v=>$l):?><option value="<?=cs_h($v)?>"><?=cs_h($l)?></option><?php endforeach;?></select></label><label class="full">Private strategy note<input name="strategy_title" maxlength="180" placeholder="Internal only: what this campaign is trying to accomplish"></label><label class="full">Public title<input name="title" maxlength="180" required value="Truth Is Not Afraid of Questions"></label><label class="full">Opening hook<textarea name="hook" required>What if honest questions are not a threat to faith—but part of finding truth?</textarea></label><label class="full">Main message<textarea name="body" required>Project Unveiled invites readers to examine faith, history, and religious systems without surrendering love for God or Jesus.</textarea></label><label>Call to action<input name="cta" required value="Read Chapter One free:"></label><label>Platform<select name="platform"><?php foreach($platforms as $v=>$l):?><option value="<?=cs_h($v)?>" <?=$v===$defaultPlatform?'selected':''?>><?=cs_h($l)?></option><?php endforeach;?></select></label><label>Campaign tracking name<input name="campaign_slug" placeholder="Generated from title when blank"></label><label>Content label<input name="content_label" value="campaign-studio"></label><label class="full">Hashtags<input name="hashtags" value="#ProjectUnveiled #TruthIsNotAfraidOfQuestions"></label><div class="full"><button>Create Private Quality-Checked Draft</button><p class="help">No social post is made here. The next step is owner review, then handoff to Post Now.</p></div></form></section>
<aside class="panel preview"><div class="eyebrow">LIVE READER PREVIEW</div><div class="preview-card"><div class="meta"><span data-preview="platform">Facebook</span> · <span data-char-count>0</span> characters</div><h3 data-preview="title"></h3><p data-preview="hook"></p><div class="preview-copy" data-preview="body"></div><p><strong data-preview="cta"></strong></p><div class="preview-url" data-preview="destination_url">Clean chapter destination generated from the selected source.</div><p data-preview="hashtags"></p></div><div class="platform-previews"><details open><summary>Facebook / LinkedIn</summary><p>Full hook, message, CTA, and tracked chapter link.</p></details><details><summary>Instagram / Threads</summary><p>Visual-first caption. The publisher will prepare the platform handoff and retain owner confirmation.</p></details><details><summary>X</summary><p>The publisher will shorten copy at handoff while preserving the campaign identity.</p></details><details><summary>YouTube / TikTok</summary><p>Use the campaign as a title, description, and media brief. Upload remains manual.</p></details></div></aside></div>
<section class="panel" style="margin-top:20px"><div class="eyebrow">PRIVATE CAMPAIGN LIBRARY</div><h2>Campaign Studio drafts</h2><?php if(!$studio):?><p>No v7.2 Campaign Studio draft exists yet.</p><?php else:?><div class="draft-list"><?php foreach($studio as $d):$q=fs_draft_quality($d,$config);?><article class="draft-row"><div><div class="eyebrow"><?=cs_h(strtoupper((string)($d['status']??'draft')))?> · <?=cs_h($d['id']??'')?></div><h3><?=cs_h($d['title']??'Campaign')?></h3><div class="meta"><?=cs_h($platforms[$d['platform']??'facebook']??$d['platform']??'')?> · <?=cs_h($d['campaign_slug']??'')?> · <?=cs_h($d['destination_url']??'')?></div><div class="score <?=!empty($q['blocked'])?'blocked':''?>"><strong><?=cs_h($q['score']??0)?></strong><span>/100 · <?=cs_h(strtoupper($q['status']??'review'))?></span></div><?php if(!empty($q['critical'])):?><ul class="issues"><?php foreach($q['critical'] as $i):?><li><?=cs_h($i)?></li><?php endforeach;?></ul><?php endif;?></div><div class="draft-actions"><?php if(empty($q['blocked'])):?><form method="post"><input type="hidden" name="csrf" value="<?=cs_h($csrf)?>"><input type="hidden" name="action" value="load_publisher"><input type="hidden" name="id" value="<?=cs_h($d['id']??'')?>"><button>Load Into Post Now</button></form><?php endif;?><form method="post"><input type="hidden" name="csrf" value="<?=cs_h($csrf)?>"><input type="hidden" name="action" value="delete_campaign"><input type="hidden" name="id" value="<?=cs_h($d['id']??'')?>"><button class="secondary">Delete</button></form></div></article><?php endforeach;?></div><?php endif;?></section>
</div></body></html>
