<?php
declare(strict_types=1);
header('Content-Type:text/html; charset=UTF-8');header('Cache-Control:no-store,max-age=0');header('X-Robots-Tag:noindex,nofollow,noarchive');header('X-Frame-Options:DENY');
require __DIR__.'/bootstrap.php';
try{$config=fs_config();}catch(Throwable $e){http_response_code(503);exit('Configuration unavailable');}
$env=fs_env();session_name('pu_private_funnel_servant');session_set_cookie_params(['lifetime'=>0,'path'=>'/owner/funnel-servant/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']);session_start();
if(empty($_SESSION['authenticated'])||empty($_SESSION['last_seen'])||time()-(int)$_SESSION['last_seen']>14400){header('Location:/owner/funnel-servant/');exit;}$_SESSION['last_seen']=time();
function osh(string $s):string{return htmlspecialchars($s,ENT_QUOTES,'UTF-8');}

$items=[];$community=fs_read_json($env['data_dir'].'/community-submissions.json',[]);if(is_array($community)){foreach($community as $r)if(is_array($r)&&($r['status']??'pending')==='pending')$items[]=['Reader moderation','A reader submission is waiting for approval.','/owner/funnel-servant/?tab=community'];}
$drafts=fs_read_json($env['data_dir'].'/drafts.json',[]);if(is_array($drafts)){foreach($drafts as $d)if(is_array($d)&&(($d['status']??'')==='draft')&&empty($d['quality_blocked'])&&empty($d['quality']['blocked']))$items[]=['Campaign review','A campaign draft is waiting for owner review.','/owner/funnel-servant/?tab=drafts'];}
if(!is_file(__DIR__.'/index.php')||!is_file(__DIR__.'/bootstrap.php'))$items[]=['System health','Owner application files need attention.','/owner/funnel-servant/command-center.php'];
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Notifications</title><style>:root{--bg:#080705;--panel:#12100b;--line:#725923;--gold:#e4b951;--cream:#f4ead2;--muted:#b9ad95;--green:#62df98}*{box-sizing:border-box}body{margin:0;background:#080705;color:var(--cream);font:16px/1.55 Arial}main{max-width:1120px;margin:auto;padding:34px 20px 80px}a{color:var(--gold)}h1,h2,h3{font-family:Georgia;color:var(--gold)}.bar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:22px}.bar a{padding:10px 13px;border:1px solid var(--line);text-decoration:none}.panel{padding:20px;border:1px solid var(--line);background:var(--panel);margin:12px 0}.muted{color:var(--muted)}input{width:100%;padding:13px;background:#050504;color:white;border:1px solid var(--line);font-size:1rem}.results{display:grid;gap:10px}.result{display:block;padding:15px;border:1px solid #3d321d;background:#0d0c09;text-decoration:none;color:var(--cream)}.result b{color:var(--gold)}.badge{display:inline-block;padding:4px 8px;border:1px solid var(--line);border-radius:99px;font-size:.72rem}.ok{color:var(--green)}</style></head><body><main><nav class="bar"><a href="command-center.php">Command Center</a><a href="search.php">Search</a></nav><h1>Notifications</h1><p class="muted">Actionable owner alerts only.</p><?php if(!$items):?><section class="panel"><h2 class="ok">All clear</h2><p>No pending owner action was detected.</p></section><?php else:foreach($items as $i):?><a class="result" href="<?=osh($i[2])?>"><b><?=osh($i[0])?></b><div class="muted"><?=osh($i[1])?></div></a><?php endforeach;endif;?></main></body></html>