<?php
declare(strict_types=1);
header('Content-Type:text/html; charset=UTF-8');header('Cache-Control:no-store,max-age=0');header('X-Robots-Tag:noindex,nofollow,noarchive');header('X-Frame-Options:DENY');
require __DIR__.'/bootstrap.php';
try{$config=fs_config();}catch(Throwable $e){http_response_code(503);exit('Configuration unavailable');}
$env=fs_env();session_name('pu_private_funnel_servant');session_set_cookie_params(['lifetime'=>0,'path'=>'/owner/funnel-servant/','secure'=>true,'httponly'=>true,'samesite'=>'Strict']);session_start();
if(empty($_SESSION['authenticated'])||empty($_SESSION['last_seen'])||time()-(int)$_SESSION['last_seen']>14400){header('Location:/owner/funnel-servant/');exit;}$_SESSION['last_seen']=time();
function osh(string $s):string{return htmlspecialchars($s,ENT_QUOTES,'UTF-8');}

$q=trim((string)($_GET['q']??''));$results=[];
function add_result(array &$r,string $kind,string $title,string $text,string $href):void{$r[]=['kind'=>$kind,'title'=>$title,'text'=>$text,'href'=>$href];}
if($q!==''){$needle=mb_strtolower($q);
 $drafts=fs_read_json($env['data_dir'].'/drafts.json',[]);if(is_array($drafts))foreach($drafts as $d){if(!is_array($d))continue;$hay=mb_strtolower(json_encode($d));if(str_contains($hay,$needle))add_result($results,'Campaign',(string)($d['title']??$d['public_title']??'Campaign'),(string)($d['status']??'draft'),'/owner/funnel-servant/?tab=drafts');}
 $community=fs_read_json($env['data_dir'].'/community-submissions.json',[]);if(is_array($community))foreach($community as $r){if(!is_array($r))continue;$hay=mb_strtolower(json_encode($r));if(str_contains($hay,$needle))add_result($results,'Reader',(string)($r['name']??'Reader submission'),mb_substr((string)($r['body']??$r['review']??''),0,180),'/owner/funnel-servant/?tab=community');}
 $book=dirname(__DIR__,2).'/book/read';foreach(glob($book.'/*.html')?:[] as $f){$txt=@file_get_contents($f);if($txt===false)continue;$title=basename($f);if(preg_match('/<title>(.*?)<\/title>/is',$txt,$m))$title=trim(strip_tags($m[1]));if(str_contains(mb_strtolower($title.' '.strip_tags($txt)),$needle))add_result($results,'Book',$title,'Book page','/book/read/'.basename($f));if(count($results)>80)break;}
 $log=$env['data_dir'].'/action-log.jsonl';if(is_file($log)){$lines=array_slice(file($log,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[],-300);foreach(array_reverse($lines) as $line){$r=json_decode($line,true);if(is_array($r)&&str_contains(mb_strtolower($line),$needle))add_result($results,'Log',(string)($r['type']??'log'),(string)($r['message']??''),'/owner/funnel-servant/?tab=logs');if(count($results)>100)break;}}
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Global Search</title><style>:root{--bg:#080705;--panel:#12100b;--line:#725923;--gold:#e4b951;--cream:#f4ead2;--muted:#b9ad95;--green:#62df98}*{box-sizing:border-box}body{margin:0;background:#080705;color:var(--cream);font:16px/1.55 Arial}main{max-width:1120px;margin:auto;padding:34px 20px 80px}a{color:var(--gold)}h1,h2,h3{font-family:Georgia;color:var(--gold)}.bar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:22px}.bar a{padding:10px 13px;border:1px solid var(--line);text-decoration:none}.panel{padding:20px;border:1px solid var(--line);background:var(--panel);margin:12px 0}.muted{color:var(--muted)}input{width:100%;padding:13px;background:#050504;color:white;border:1px solid var(--line);font-size:1rem}.results{display:grid;gap:10px}.result{display:block;padding:15px;border:1px solid #3d321d;background:#0d0c09;text-decoration:none;color:var(--cream)}.result b{color:var(--gold)}.badge{display:inline-block;padding:4px 8px;border:1px solid var(--line);border-radius:99px;font-size:.72rem}.ok{color:var(--green)}</style></head><body><main><nav class="bar"><a href="command-center.php">Command Center</a><a href="?tab=drafts">Campaign Studio</a><a href="notifications.php">Notifications</a></nav><h1>Global Search</h1><p class="muted">Search campaigns, reader submissions, book pages, and recent system logs.</p><form><input name="q" value="<?=osh($q)?>" placeholder="Search Project Unveiled OS" autofocus></form><?php if($q!==''):?><h2><?=count($results)?> result<?=count($results)===1?'':'s'?></h2><div class="results"><?php foreach($results as $r):?><a class="result" href="<?=osh($r['href'])?>"><span class="badge"><?=osh($r['kind'])?></span><br><b><?=osh($r['title'])?></b><div class="muted"><?=osh($r['text'])?></div></a><?php endforeach;?><?php if(!$results):?><div class="panel">No matching records.</div><?php endif;?></div><?php endif;?></main></body></html>